name: Generate Animated Black Hole SVG

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate blackhole SVG
        run: python generate_blackhole.py

      - name: Commit and push SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update animated blackhole SVG"
          files: "blackhole_animation.svg"
          branch: main # Or your default branch